all: Administrador.o Cadastro.o CalendarioDeEventos.o Data.o Endereco.o Evento.o Hora.o Login.o Menu.o Perfil.o PortalDeInformacoes.o Usuario.o Main.cpp
	g++ -o TP01 Main.cpp Administrador.o Cadastro.o CalendarioDeEventos.o Data.o Endereco.o Evento.o Hora.o Login.o Menu.o Perfil.o PortalDeInformacoes.o Usuario.o

run:
	./TP01